apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-stack
  labels:
    app: grafana-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-stack
  template:
    metadata:
      labels:
        app: grafana-stack
    spec:
      containers:
      - name: grafana
        image: docker.io/grafana/grafana:latest
        ports:
          - containerPort: 3000
            hostPort: 3000
            protocol: TCP
        volumeMounts:
          - mountPath: /etc/grafana/grafana.ini:Z
            name: grafana-config
          - mountPath: /var/lib/grafana:Z
            name: grafana
          - mountPath: /etc/grafana/provisioning:Z
            name: grafana-provisioning
        securityContext:
          runAsUser: 0
      - name: tempo
        image: docker.io/grafana/tempo:latest
        args:
        - --config.file=/mnt/config/tempo-local-config.yaml
        ports:
          - containerPort: 3200
            hostPort: 3200
            protocol: TCP
          - containerPort: 4317
            hostPort: 4317
            protocol: TCP
          - containerPort: 4318
            hostPort: 4318
            protocol: TCP
          - containerPort: 9097
            hostPort: 9097
            protocol: TCP
          - containerPort: 9411
            hostPort: 9411
            protocol: TCP
          - containerPort: 14268
            hostPort: 14268
            protocol: TCP
        volumeMounts:
          - mountPath: /tmp/tempo:Z
            name: tempo
          - mountPath: /mnt/config/tempo-local-config.yaml:Z
            name: tempo-config
        securityContext:
          runAsUser: 0
      volumes:
      - hostPath:
          path: ./grafana/data
          type: Directory
        name: grafana
      - hostPath:
          path: ./grafana/grafana.ini
          type: File
        name: grafana-config
      - hostPath:
          path: ./grafana/provisioning
          type: Directory
        name: grafana-provisioning
      - hostPath:
          path: ./tempo/data
          type: Directory
        name: tempo
      - hostPath:
          path: ./tempo/tempo-local-config.yaml
          type: File
        name: tempo-config
