apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-stack
  labels:
    app: grafana-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-stack
  template:
    metadata:
      labels:
        app: grafana-stack
    spec:
      containers:
        - name: grafana
          image: docker.io/grafana/grafana:latest
          ports:
            - containerPort: 3000
              hostPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/grafana/grafana.ini:Z
              name: grafana-config
            - mountPath: /var/lib/grafana:Z
              name: grafana
            - mountPath: /etc/grafana/provisioning:Z
              name: grafana-provisioning
            - mountPath: /var/lib/grafana/dashboards:Z
              name: grafana-dashboards
          securityContext:
            runAsUser: 0
        - name: vlogs
          image: docker.io/victoriametrics/victoria-logs:v1.17.0-victorialogs
          args:
            - --retentionPeriod=1y
            - --logIngestedRows=true
            - --loki.maxRequestSize=128Mb
          ports:
            - containerPort: 9428
              hostPort: 9428
              protocol: TCP
          volumeMounts:
            - mountPath: /victoria-logs-data:Z
              name: vlogs
      volumes:
        - hostPath:
            path: ./grafana/data
            type: Directory
          name: grafana
        - hostPath:
            path: ./grafana/grafana.ini
            type: File
          name: grafana-config
        - hostPath:
            path: ./grafana/provisioning
            type: Directory
          name: grafana-provisioning
        - hostPath:
            path: ./grafana/dashboards
            type: Directory
          name: grafana-dashboards
        - hostPath:
            path: ./vlogs/data
            type: Directory
          name: vlogs
