{
 "title": "Audit log",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ds",
    "query": "victoriametrics-logs-datasource"
   },
   { "name": "username", "label": "Username", "query": { "query": "" } },
   { "name": "verb", "label": "Verb", "query": { "query": "" } },
   { "name": "objRefResource", "label": "Resource", "query": { "query": "" } },
   { "name": "objRefNamespace", "label": "Namespace", "query": ".*" },
   { "name": "objRefSubresource", "label": "Subresource", "query": "(^$|status)" }
  ]
 },
 "panels": [
  {
   "title": "Matched audit log events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "direction": "desc",
       "expr": "user.username: ${username} verb: ${verb} objectRef.resource: ${objRefResource} objectRef.namespace:~\"${objRefNamespace}\" objectRef.subresource:~\"${objRefSubresource}\"",
       "maxLines": 100
      }
     ]
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Slow operations per username",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "user.username:${username} verb:${verb} objectRef.resource:${objRefResource} objectRef.namespace:~\"${objRefNamespace}\" objectRef.subresource:~\"${objRefSubresource}\" | annotations.apiserver.latency.k8s.io/total:* | math \"annotations.apiserver.latency.k8s.io/total\" as total_latency | stats by (user.username) sum(total_latency) sum_total | sum_total:>5s"
    }
   ]
  },
  {
   "title": "Long etcd operations per username",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "user.username:${username} verb:${verb} objectRef.resource:${objRefResource} objectRef.namespace:~\"${objRefNamespace}\" objectRef.subresource:~\"${objRefSubresource}\" | annotations.apiserver.latency.k8s.io/etcd: * | math \"annotations.apiserver.latency.k8s.io/etcd\" as total_latency | stats by (user.username) sum(total_latency) sum_total | sum_total:>5s"
    }
   ]
  },
  {
   "title": "APF queue wait per username",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "user.username:${username} verb:${verb} objectRef.resource:${objRefResource} objectRef.namespace:~\"${objRefNamespace}\" objectRef.subresource:~\"${objRefSubresource}\" | annotations.apiserver.latency.k8s.io/apf-queue-wait:* | math \"annotations.apiserver.latency.k8s.io/apf-queue-wait\" as total_latency | stats by (user.username) sum(total_latency) sum_total | sum_total:>50ms"
    }
   ]
  },
  {
   "title": "Large write operations per username",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "user.username:${username} verb:${verb} objectRef.resource:${objRefResource} objectRef.namespace:~\"${objRefNamespace}\" objectRef.subresource:~\"${objRefSubresource}\" | annotations.apiserver.latency.k8s.io/response-write:* | math \"annotations.apiserver.latency.k8s.io/response-write\" as total_latency | stats by (user.username) sum(total_latency) sum_total | sum_total:>50ms"
    }
   ]
  },
  {
   "title": "Long mutating webhook operations per username",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "user.username:${username} verb:${verb} objectRef.resource:${objRefResource} objectRef.namespace:~\"${objRefNamespace}\" objectRef.subresource:~\"${objRefSubresource}\" | annotations.apiserver.latency.k8s.io/mutating-webhook:* | math \"annotations.apiserver.latency.k8s.io/mutating-webhook\" as total_latency | stats by (user.username) sum(total_latency) sum_total | sum_total:>50ms"
    }
   ]
  },
  {
   "title": "Decode response object per username",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "user.username:${username} verb:${verb} objectRef.resource:${objRefResource} objectRef.namespace:~\"${objRefNamespace}\" objectRef.subresource:~\"${objRefSubresource}\" | annotations.apiserver.latency.k8s.io/decode-response-object:* | math \"annotations.apiserver.latency.k8s.io/decode-response-object\" as total_latency | stats by (user.username) sum(total_latency) sum_total | sum_total:>10ms"
    }
   ]
  },
  {
   "title": "Transform response object per username",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "user.username:${username} verb:${verb} objectRef.resource:${objRefResource} objectRef.namespace:~\"${objRefNamespace}\" objectRef.subresource:~\"${objRefSubresource}\" | annotations.apiserver.latency.k8s.io/transform-response-object:* | math \"annotations.apiserver.latency.k8s.io/transform-response-object\" as total_latency | stats by (user.username) sum(total_latency) sum_total | sum_total:>10ms"
    }
   ]
  },
  {
   "title": "Serialize response object per username",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "user.username:${username} verb:${verb} objectRef.resource:${objRefResource} objectRef.namespace:~\"${objRefNamespace}\" objectRef.subresource:~\"${objRefSubresource}\" | annotations.apiserver.latency.k8s.io/serialize-response-object:* | math \"annotations.apiserver.latency.k8s.io/serialize-response-object\" as total_latency | stats by (user.username) sum(total_latency) sum_total | sum_total:>10ms"
    }
   ]
  },
  { "title": "Hits", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Operations per username",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "user.username:${username} verb:${verb} objectRef.resource:${objRefResource} objectRef.namespace:~\"${objRefNamespace}\" objectRef.subresource:~\"${objRefSubresource}\" | stage:ResponseComplete | stats by (user.username) count() per_stream_logs | per_stream_logs:>500"
    }
   ]
  },
  {
   "title": "Operations per resource",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "user.username:${username} verb:${verb} objectRef.resource:${objRefResource} objectRef.namespace:~\"${objRefNamespace}\" objectRef.subresource:~\"${objRefSubresource}\" | stage:ResponseComplete | stats by (objectRef.apiVersion, objectRef.apiGroup, objectRef.resource) count() per_stream_logs | per_stream_logs:>500"
    }
   ]
  },
  {
   "title": "Operations per verb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "user.username:${username} verb:${verb} objectRef.resource:${objRefResource} objectRef.namespace:~\"${objRefNamespace}\" objectRef.subresource:~\"${objRefSubresource}\" | stage:ResponseComplete | stats by (verb) count() per_stream_logs | per_stream_logs:>500"
    }
   ]
  },
  {
   "title": "Operations per namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "user.username:${username} verb:${verb} objectRef.resource:${objRefResource} objectRef.namespace:~\"${objRefNamespace}\" objectRef.subresource:~\"${objRefSubresource}\" | stage:ResponseComplete | stats by (objectRef.namespace) count() per_stream_logs | per_stream_logs:>500"
    }
   ]
  },
  {
   "title": "Operations per resource",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "user.username:${username} verb:${verb} objectRef.resource:${objRefResource} objectRef.namespace:~\"${objRefNamespace}\" objectRef.subresource:~\"${objRefSubresource}\" | stage:ResponseComplete AND verb:\"list\" | stats by (objectRef.apiGroup, objectRef.apiVersion, objectRef.resource) count() per_stream_logs | per_stream_logs:>100"
    }
   ]
  },
  {
   "title": "Mutating operators per resource",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "user.username:${username} verb:${verb} objectRef.resource:${objRefResource} objectRef.namespace:~\"${objRefNamespace}\" objectRef.subresource:~\"${objRefSubresource}\" | stage:ResponseComplete AND verb:~\"create|update|patch|delete\" | stats by (objectRef.apiGroup, objectRef.apiVersion, objectRef.resource) count() per_stream_logs | per_stream_logs:>500"
    }
   ]
  },
  {
   "title": "Operations per subresource",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "user.username:${username} verb:${verb} objectRef.resource:${objRefResource} objectRef.namespace:~\"${objRefNamespace}\" objectRef.subresource:~\"${objRefSubresource}\" | stage:ResponseComplete | stats by (objectRef.subresource) count() per_stream_logs"
    }
   ]
  },
  { "title": "Deprecations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Deprecated requests per resource",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "user.username:${username} verb:${verb} objectRef.resource:${objRefResource} objectRef.namespace:~\"${objRefNamespace}\" objectRef.subresource:~\"${objRefSubresource}\" | annotations.k8s.io/deprecated:* | stats by (objectRef.apiVersion, objectRef.apiGroup, objectRef.resource) count() per_stream_logs | per_stream_logs:>10"
    }
   ]
  },
  {
   "title": "Deprecated resource requests by user",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "targets": [
    {
     "expr": "user.username:${username} verb:${verb} objectRef.resource:${objRefResource} objectRef.namespace:~\"${objRefNamespace}\" objectRef.subresource:~\"${objRefSubresource}\" | annotations.k8s.io/deprecated:* | stats by (user.username) count() per_stream_logs | per_stream_logs:>50"
    }
   ]
  },
  {
   "title": "Unready apiserver",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "collapsed": true,
   "panels": [
    {
     "title": "Non-loopback unready requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
     "targets": [
      {
       "expr": "user.username:${username} verb:${verb} objectRef.resource:${objRefResource} objectRef.namespace:~\"${objRefNamespace}\" objectRef.subresource:~\"${objRefSubresource}\"| annotations.openshift.io/unready:~\"loopback=false\" | stats by (objectRef.apiVersion, objectRef.apiGroup, objectRef.resource) count() per_stream_logs"
      }
     ]
    },
    {
     "title": "Loopback requests when kube-apiserver not ready",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
     "targets": [
      {
       "expr": "user.username:${username} verb:${verb} objectRef.resource:${objRefResource} objectRef.namespace:~\"${objRefNamespace}\" objectRef.subresource:~\"${objRefSubresource}\"| annotations.openshift.io/unready:~\"loopback=true\" | stats by (user.username) count() per_stream_logs"
      }
     ]
    }
   ]
  }
 ]
}